title: Page

columns:
  main:
    width: 2/3
    sections:
      content:
        type: fields
        fields:
          text:
            label: Text
            type: textarea
            size: large
  sidebar:
    width: 1/3
    sections:
      files:
        type: files
        headline: Files
      sidebar:
        type: fields
        fields:
          year:
            label: Year
            type: number
            default: 2019
          place:
            label: Place
            type: text
          type:
            label: Type
            type: select
            options:
              exhibition: Exhibition
              publication: Publication
          show_in_archive:
            label: Show in archive
            type: toggle
            default: true
          text_color:
            label: Text Color
            type: color
            editableAlpha: false # (optional) if set to false, alpha value controls are not displayed
            default: "rgb(60, 32, 99)"
          bg_color:
            label: Background Color
            type: color
            editableAlpha: false # (optional) if set to false, alpha value controls are not displayed
            default: "rgb(196, 196, 196)"

