title: Site
# preset: pages
unlisted: true
sections:
  episodes:
    headline: Main
    type: pages
    status: all
    info: "{{ page.intendedTemplate }}"
    image: false
    templates:
      - home
      - archive
  projects:
    headline: Projects
    type: pages
    status: all
    info: "{{ page.intendedTemplate }}"
    image: false
    templates:
      - default
