title: Site
# preset: pages
unlisted: true
sections:
  drafts:
    extends: sections/pages
    headline: Drafts
    status: draft
  published:
    extends: sections/pages
    headline: Published
    status: published
